### ISSUE TITLE
图库管理页面翻译提交

### ISSUE THREAD

**Issue by Yanstory** [EhTagTranslation/EhSyringe#1035]
**相关页面**
upload (.ts)

**原文**
View
Disown
Gallery Category
The publicly listed category for this gallery.
Gallery Language
The primary language for this gallery. Can only be changed here for new unpublished galleries; set with tags for published/updated galleries.

_一个语言列表，其中：_
- Common
- Textless
  - Speechless
  - Text Cleaned
- Others

Official / Textless
Translated
Rewrite
You can write an optional uploader comment here.
Disown Gallery

**翻译**
查看
放弃所有权（舍弃/放弃管理？这个功能会把上传者名字从图库中移除，同时移除上传者对该图库的管理权）
图库分类
图库在公开列表中的所属分类。
图库语言
此图库的首选阅读语言。仅新建立且未发布的图库可更改此选项，会为已发布/更新的图库添加标签。

_一个语言列表，其中：_
- 常见
- 无文字
  - 无对话
  - 抹除文字版
- 其它

官方 / 无字
翻译版
重写版
在此处按需写下上传者评论。
放弃图库

**Comment by OpportunityLiu** [comment]
我没发过，有些选项看不到，除非你给我发页面源代码，否则我这里没法确定原始字符串。

**Comment by Yanstory** [comment]
修正了 `Official` （手打出错了），其它的字符串也重新CV了一遍。

这里已经是原文和对照译文了，如果是语言列表的话，基本上都是一些已有语言，除了一个特例：

<details>
  <summary>语言列表（英文）</summary>

- Common
  - Japanese / Other
  - Chinese
  - English
  - French
  - Korean
  - Portuguese
  - Russian
  - Spanish
- Textless
  - Speechless
  - Text Cleaned
- Others
  - Albanian
  - Arabic
  - Bulgarian
  - Catalan
  - Cebuano
  - Croatian
  - Czech
  - Dutch
  - Esperanto
  - Finnish
  - German
  - Greek
  - Hindi
  - Hungarian
  - Indonesian
  - Italian
  - Javanese
  - Latin
  - Norwegian
  - Persian
  - Polish
  - Romanian
  - Slovak
  - Swedish
  - Tagalog
  - Thai
  - Turkish
  - Ukrainian
  - Vietnamese

</details>

<details>
  <summary>语言列表（中文）</summary>

- 常见
  - 日文 / 其它
  - 中文
  - 英文
  - 法文
  - 韩文
  - 葡萄牙文
  - 俄文
  - 西班牙文
- 无文字
  - 无对话
  - 抹除文字版
- 其它
  - 阿尔巴尼亚语
  - 阿拉伯语
  - 保加利亚语
  - 加泰罗尼亚语
  - 塞布亚诺
  - 克罗地亚语
  - 捷克语
  - 荷兰语
  - 世界语
  - 芬兰语
  - 德语
  - 希腊语
  - 印地语
  - 匈牙利语
  - 印尼语
  - 意大利语
  - 爪哇语
  - 拉丁语
  - 挪威语
  - 波斯语
  - 波兰语
  - 罗马尼亚语
  - 斯洛伐克语
  - 瑞典语
  - 他加禄语
  - 泰语
  - 土耳其语
  - 乌克兰语
  - 越南语

</details>
