### ISSUE TITLE
数据库更新停止在了8月20日

### ISSUE THREAD

**Issue by nomosaic** [EhTagTranslation/EhSyringe#1051]
**描述问题**
数据库更新停止在了8月20日，但可以检查到有新的数据库版本，gitcdn.xyz一直无法连接上，全局代理也没用，脚本版和扩展版都一样，不知道是不是这个原因没法更新，但chrome系的浏览器却可以正常更新
**相关网址**

**截图**
![EhSyringe无法更新数据](https://user-images.githubusercontent.com/14254798/198608952-91e6bc0c-f533-4faa-91aa-2d513ebfd5b2.jpg)

**环境**

-   系统：Windows 7 SP1 x64
-   浏览器：Waterfox Classic 2022.08 x64
-   插件版本：2.8.14

**Comment by OpportunityLiu** [comment]
还不行吗？gitcdn.xyz 确实出问题了，但是其他的 cdn 应该没事啊

**Comment by OpportunityLiu** [comment]
如果还有问题再新开 issue 吧，很多上下文已经失效了
