### ISSUE TITLE
通过 AdGuard 的脚本管理器使用时，标签没有被翻译

### ISSUE THREAD

**Issue by ZeroClover** [EhTagTranslation/EhSyringe#1057]
**描述问题**

通过 AdGuard 的脚本管理器使用时，标签没有被翻译

**相关网址**

All

**截图**

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/13190004/200883710-d9ec9232-287a-48c2-ada9-0e886dd05fbb.png">

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/13190004/200883784-fb0b197a-d2b8-4b39-818f-fd371252de49.png">

**环境**

-   系统: macOS 13.0
-   浏览器: Microsoft Edge 107
-   插件版本: 2.8.14

**Comment by OpportunityLiu** [comment]
f12 控制台有报错吗

**Comment by ZeroClover** [comment]
> f12 控制台有报错吗

看起来没有

<img width="547" alt="image" src="https://user-images.githubusercontent.com/13190004/200889340-367d5ca8-c10a-44a3-8906-070a016ed1c5.png">

**Comment by OpportunityLiu** [comment]
是不是在设置里把翻译标签关了啊

**Comment by ZeroClover** [comment]
> 是不是在设置里把翻译标签关了啊

<img width="263" alt="image" src="https://user-images.githubusercontent.com/13190004/200975911-845f9c6c-6370-4dfc-9ba5-173d3f5eec46.png">

**Comment by OpportunityLiu** [comment]
是最近哪个版本才不能用的吗？之前有支持过 adguard #597 

用这个加载呢？
```
(function () {
    if (/(^|\.)e[-x]hentai\.org$/i.test(location.hostname) && !document.getElementById('EhSyringe-Script')) {
        var script = document.createElement('script');
        script.id = 'EhSyringe-Script';
        script.src = 'https://sleazyfork.org/scripts/407833-ehsyringe/code/EhSyringe.user.js';
        document.documentElement.append(script);
    }
})();
```

**Comment by OpportunityLiu** [comment]
我装了个 Windows 版也没啥问题啊

**Comment by ZeroClover** [comment]
> 是最近哪个版本才不能用的吗？之前有支持过 adguard #597
> 
> 用这个加载呢？
> 
> ```
> (function () {
>     if (/(^|\.)e[-x]hentai\.org$/i.test(location.hostname) && !document.getElementById('EhSyringe-Script')) {
>         var script = document.createElement('script');
>         script.id = 'EhSyringe-Script';
>         script.src = 'https://sleazyfork.org/scripts/407833-ehsyringe/code/EhSyringe.user.js';
>         document.documentElement.append(script);
>     }
> })();
> ```

用这个可以正常加载标签的翻译

之前用的都是浏览器插件，但是感觉在多个设备上不停手动装插件比较麻烦就打算换用 UserScript

还没测试过 Windows 上的 AdGuard 能不能用，之后试试看

**Comment by OpportunityLiu** [comment]
我这没mac也测不了  @xioxin

**Comment by xioxin** [comment]
我在mac上安装了AdGuard for Safari 但是没有找到脚本管理器。
你可以试试这个浏览器插件 https://github.com/quoid/userscripts 适用于iOS和macOS的Safari

**Comment by ZeroClover** [comment]
> 我在mac上安装了AdGuard for Safari 但是没有找到脚本管理器。 你可以试试这个浏览器插件 https://github.com/quoid/userscripts 适用于iOS和macOS的Safari

浏览器插件版本没有脚本管理器功能，只有应用程序有。

主要是用 AdGuard 可以跨浏览器使用脚本，相当而言比较方便

**Comment by OpportunityLiu** [comment]
@xioxin 应用程序版本是 代理+自签证书+MITM 直接注入脚本的，执行环境和插件很不一样，不需要特定浏览器
