### ISSUE TITLE
新版本 Tampermonkey 下偶尔无法正常工作

### ISSUE THREAD

**Issue by xb2016** [EhTagTranslation/EhSyringe#1116]
**描述问题**

Tampermonkey for Microsoft  Edge 在 2023-01-06 更新了 4.18.1 版本，更新后 E 站 UI 偶尔会有部分内容未翻译。
测试了两台设备，更新 Tampermonkey 后均产生了此问题，不知道油猴改了啥。

**截图**

![20221004](https://user-images.githubusercontent.com/31783875/212050638-d3c0810d-af9d-498b-8d12-9e014c831ed9.gif)

**环境**

-   系统：Windows 10 22H2 PW
-   浏览器：Microsoft Edge 108.0.1462.76
-   Tampermonkey 版本：4.18.1
-   EhSyringe 版本：2.9.1

**Comment by OpportunityLiu** [comment]
加载顺序问题，最好还是把注入模式改成“即时”

![image](https://user-images.githubusercontent.com/13471233/213090093-4147825b-788c-491e-81de-ffea0b04c70f.png)
