### ISSUE TITLE
![image](https://user-images.githubusercontent.com/65083224/214225235-e9badbd9-96d2-4394-ab96-03b863cf1aa7.png)

### ISSUE THREAD

**Issue by OpportunityLiu** [EhTagTranslation/EhSyringe#1129]
![image](https://user-images.githubusercontent.com/65083224/214225235-e9badbd9-96d2-4394-ab96-03b863cf1aa7.png)

这句话没有翻译到

https://github.com/EhTagTranslation/EhSyringe/pull/1118

_Originally posted by @o-liverkk in https://github.com/EhTagTranslation/EhSyringe/issues/1117#issuecomment-1401448191_

**Comment by xb2016** [comment]
![image](https://user-images.githubusercontent.com/31783875/214748400-63c0a90d-95cf-45fb-bbd4-f4c5300056cc.png)
我这是 2000 啊，这还能不一样的？

**Comment by o-liverkk** [comment]
我这五个client都是 1000 , 可能和申请时间有关?
![image](https://user-images.githubusercontent.com/65083224/214751258-ce0e0a1a-2318-45d8-9d01-30be59adeffd.png)

**Comment by xb2016** [comment]
已在 #1125 修复
