### ISSUE TITLE
请关注[Hentai@Home]修改

### ISSUE THREAD

**Issue by o-liverkk** [EhTagTranslation/EhSyringe#1133]
如图, H@H 又修改了

![image](https://user-images.githubusercontent.com/65083224/216551268-f418f5e1-d8f9-4078-a9c8-40547b2c41bd.png)

**Comment by 1235789gzy1** [comment]
![InkedFireShot Capture 036 - E-Hentai Galleries - The Free Hentai Doujinshi, Manga and Image Galle_ - e-hentai org](https://user-images.githubusercontent.com/52618207/235335892-f5c29583-6739-4a8c-b57c-7fef439c341e.jpg)

似乎又改了

**Comment by o-liverkk** [comment]
> ![InkedFireShot Capture 036 - E-Hentai Galleries - The Free Hentai Doujinshi, Manga and Image Galle_ - e-hentai org](https://user-images.githubusercontent.com/52618207/235335892-f5c29583-6739-4a8c-b57c-7fef439c341e.jpg)
> 
> 似乎又改了

无法证实

**Comment by 1235789gzy1** [comment]
![image](https://user-images.githubusercontent.com/52618207/235346532-85583ed2-f872-4218-a231-6fbcda58dc26.png)

chrome和Edge均无法完全翻译，火狐浏览器完全正常；
Edge尝试全新环境（新建角色且仅加载EhSyringe），仍然无法完全翻译

**Comment by o-liverkk** [comment]
> ![image](https://user-images.githubusercontent.com/52618207/235346532-85583ed2-f872-4218-a231-6fbcda58dc26.png)
> 
> chrome和Edge均无法完全翻译，火狐浏览器完全正常； Edge尝试全新环境（新建角色且仅加载EhSyringe），仍然无法完全翻译

最新版是2.9.10，你落后一个大版本了
https://github.com/EhTagTranslation/EhSyringe/releases/tag/v2.9.10

**Comment by 1235789gzy1** [comment]
> > ![image](https://user-images.githubusercontent.com/52618207/235346532-85583ed2-f872-4218-a231-6fbcda58dc26.png)
> > chrome和Edge均无法完全翻译，火狐浏览器完全正常； Edge尝试全新环境（新建角色且仅加载EhSyringe），仍然无法完全翻译
> 
> 最新版是2.9.10，你落后一个大版本了 https://github.com/EhTagTranslation/EhSyringe/releases/tag/v2.9.10

草，看起来今天没带脑子，偷懒只更新tag没更新插件版本（
