### ISSUE TITLE
（订阅->我的标签）标签输入框没有注射

### ISSUE THREAD

**Issue by aaronchen233** [EhTagTranslation/EhSyringe#1187]
**描述你想要的功能**
我希望能给（订阅->我的标签）里的标签输入框打一针

**Comment by Mapaler** [comment]
![firefox_0105](https://github.com/EhTagTranslation/EhSyringe/assets/6565860/3ff8bf41-e308-481d-bbba-cb826a60e465)
是指的这个地方没有标签提示吗？
