### ISSUE TITLE
有关在浏览器工具栏切换搜索站点

### ISSUE THREAD

**Issue by ACEZEROONE** [EhTagTranslation/EhSyringe#1191]
输入ex关键字按tab后搜索默认的搜索框是表站的，希望能给个按钮切换到里站的搜索引擎

**Comment by OpportunityLiu** [comment]
你开一个里站的标签页以后再用就是搜里站了

**Comment by ACEZEROONE** [comment]
好吧，我明白了，是打开ex的标签页在该标签页的工具栏上搜索，但这也太麻烦了，希望能优化一下吧
