### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023

### ISSUE THREAD

**Issue by qq000945** [EhTagTranslation/EhSyringe#1194]
![2023-06-15_195018](https://github.com/EhTagTranslation/EhSyringe/assets/67133551/13a3a4ee-f9df-45fb-bafb-fd74e7750dd5)
软件已经不被新版本谷歌浏览器支持了，我的天，急急急!

试了百度上的办法，手动把版本号改成3，无法运行扩展

**Comment by qq000945** [comment]
![QQ截图20230615195259](https://github.com/EhTagTranslation/EhSyringe/assets/67133551/80b3bf54-567a-4e57-8fc2-dc6fef2c0b09)

**Comment by qq000945** [comment]
It seems that Google is [postponing the phase-out of manifest V2](https://groups.google.com/u/0/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E).

I put https://github.com/Sjord/tablefilter/pull/9, but can't get it to work on both Firefox and Chrome. The existing manifest v2 is compatible with both, but Firefox and Chrome https://github.com/w3c/webextensions/issues/282 on how manifest v3 should work.

**Comment by qq000945** [comment]
谢谢大佬，已经可以用了！~
![$4YW$A$~WZ T42U)T}~V`FR](https://github.com/EhTagTranslation/EhSyringe/assets/67133551/356e0ecd-0201-41c0-822d-150792eb5f01)

**Comment by OpportunityLiu** [comment]
duplicate #813
