### ISSUE TITLE
H@H 修改了磁盘空间单位单位

### ISSUE THREAD

**Issue by o-liverkk** [EhTagTranslation/EhSyringe#1205]
H@H 修改了磁盘空间的单位（GB -> GiB, MB -> MiB）。网络流量单位保持不变。

**相关页面**
H@H服务器设置界面
https://e-hentai.org/hentaiathome.php?cid=*&act=settings
**原文**
How much disk space to reserve for this client. Must be at least 10 GiB, but the more you assign the better your client will perform. The reserved space must always be available.
**翻译**
为此客户端保留多少磁盘空间。 至少为10GiB，但分配的越多，您的客户端性能就越好。被保留空间必须始终可用。

**原文**
Static Range allocation is limited to 1 per 250 MiB of disk space.
**翻译**
静态范围分配被限制为每 250 MiB 磁盘空间分配 1 组静态范围 。

**原文**
If this value is set, the client will stop running if the free space on the disk decreases below this value. The client will exit if free space drops below 1 GiB even if this is not set.
**翻译**
如果设置了此值，则当磁盘上的可用空间低于此值时客户端会停止运行。即使未设置，当可用空间低于 1 GiB 时，客户端也会退出。

**原文**
This client currently has 1991 static range(s) assigned: P1 = 1484, P2 = 349, P3 = 85, P4 = 19, P5 = 54
**翻译**
_H@H新引入了一个体现服务器可靠性的指标，参见 https://ehwiki.org/wiki/Hentai@Home#Cache_

**Comment by sakuyamaij** [comment]
https://github.com/EhTagTranslation/EhSyringe/pull/1204 我更新了下，等大佬们再审核下了
