### ISSUE TITLE
兼容tor .union网站

### ISSUE THREAD

**Issue by dffxd-suntra** [EhTagTranslation/EhSyringe#1207]
**描述你想要的功能**
详见：http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion/
![image](https://github.com/EhTagTranslation/EhSyringe/assets/47025714/3ddb04a8-9d7e-4ce9-b94d-b77a1c91d0d0)
对于将网址加入match不管用，网站结构和ex的差不多但是画廊详情页面没有侧栏，不能投票

**Comment by OpportunityLiu** [comment]
![image](https://github.com/EhTagTranslation/EhSyringe/assets/13471233/2c505278-4f59-4af0-9f7c-53ed61d89ccf)
一切正常啊，早就支持过了
