### ISSUE TITLE
H@H界面翻译更新

### ISSUE THREAD

**Issue by 1235789gzy1** [EhTagTranslation/EhSyringe#1211]
>  2023-10-02
> 
> - China was split out as a separate region for the H@H readouts - it has been a separate region internally for some time. Note that due to the overall quirkiness of this region, the Quality readout is not available.
> 
> - H@H regional stat tracking are now based on the region of the client rather than the region of the visitor, which makes more sense overall.
> 
> - Removed the "H@H Miss%" since it was getting rather meaningless being at ~0% all the time. Added a Files/sec readout instead.
> 

今天更新了H@H界面，主要是将中国单独统计，并且添加了 点击/秒 统计
![image](https://github.com/EhTagTranslation/EhSyringe/assets/52618207/025d23da-ec34-4dfd-aad9-38b257d9930f)

**Comment by Matcha-sama** [comment]
### https://github.com/EhTagTranslation/EhSyringe/pull/1212
### https://github.com/EhTagTranslation/EhSyringe/pull/1213
![dfSMAlTO](https://github.com/EhTagTranslation/EhSyringe/assets/56059155/56291539-679b-4e99-871b-2801bfb757b5)

**Comment by 1235789gzy1** [comment]
![image](https://github.com/EhTagTranslation/EhSyringe/assets/52618207/46a34530-2239-43dc-a982-3944ca86f410)
~~菠萝怎么又动了这里的信息~~
