### ISSUE TITLE
用户同时使用 E-Hentai Downloader 脚本，下载消耗 GP 点的问题

### ISSUE THREAD

**Issue by SunBrook** [EhTagTranslation/EhSyringe#1226]
E-Hentai Downloader 脚本作者，根据 Posted 的时间来判断上传日期是否久远，来判断是否需要下载源文件（消耗 GP 点）。
这个 Posted 被翻译成中文导致判断失误，建议在翻译后，穿插一个 td 标签，用于判断

![image](https://github.com/EhTagTranslation/EhSyringe/assets/14243713/67d654c1-4e82-4595-9972-c477bd869b28)

**Comment by OpportunityLiu** [comment]
加了的，你是最新版本吗？浏览器什么版本？

**Comment by SunBrook** [comment]
好吧，是脚本版本没有更新，我更新到最新版本就好了
