### ISSUE TITLE
E-Hentai-Downloader 兼容问题

### ISSUE THREAD

**Issue by xjxyv** [EhTagTranslation/EhSyringe#1237]
**描述问题**
v2.12.1后会多出一段未翻译的信息
**相关网址**

**截图**
![屏幕截图 2024-01-15 201457](https://github.com/EhTagTranslation/EhSyringe/assets/94707100/7c8f7e3c-e4bc-468d-b5f2-109bb1e7d55f)

**环境**

-   系统: [例如: Windows Android]
-   浏览器 [例如: Chrome Firefox]
-   插件版本 [例如: 1.0.0]

**Comment by tch1121** [comment]
不知道为什么要克隆 注释掉就好了
```js
// src/plugin/syringe/index.ts
if (isElement(node, 'div') && node.id === 'gdd') {
    /* E-Hentai-Downloader 兼容处理 */
    // this.cloneAndPrependElement(node.firstElementChild!);
}

**Comment by OpportunityLiu** [comment]
> 不知道为什么要克隆 注释掉就好了
> 
> ```js
> // src/plugin/syringe/index.ts
> if (isElement(node, 'div') && node.id === 'gdd') {
>     /* E-Hentai-Downloader 兼容处理 */
>     // this.cloneAndPrependElement(node.firstElementChild!);
> }
> ```

原因在这 #1226 https://sleazyfork.org/zh-CN/scripts/407833-ehsyringe/discussions/208490
