### ISSUE TITLE
接收悬赏bug

### ISSUE THREAD

**Issue by Nana7miChiaKi** [EhTagTranslation/EhSyringe#1238]
**描述问题**
用插件点右边的接受是蓝色的，关掉插件就变成红色的了
**截图**
![Screenshot_2024-01-16_12-00-37](https://github.com/EhTagTranslation/EhSyringe/assets/75150515/ae3255b4-239f-4dec-82ee-7af9c1b98b39)
![Screenshot_2024-01-16_11-59-49](https://github.com/EhTagTranslation/EhSyringe/assets/75150515/cc2260a3-f60f-4cd0-95de-ff9661e4fd55)
**环境**
-   系统: [Windows]
-   浏览器 [Chrome]
-   插件版本 [2.12.6]

**Comment by Nana7miChiaKi** [comment]
用的是加载解扩展程序的功能安装的，不是脚本管理器，每次更新的时候都是下载新的，然后覆盖

**Comment by OpportunityLiu** [comment]
本来就是两个不同的状态。。。你刷新的档口状态变了

**Comment by Nana7miChiaKi** [comment]
> 本来就是两个不同的状态。。。你刷新的档口状态变了

没发现有什么不同，都是在未接受悬赏的状态下点了右边的按钮
https://youtu.be/RADU81gDRhk
