### ISSUE TITLE
我的标签界面“移动标签”未能翻译

### ISSUE THREAD

**Issue by 1235789gzy1** [EhTagTranslation/EhSyringe#1242]
**描述问题**
金星用户拥有十个“我的标签”文件夹，因此我的标签页面会额外多出移动标签的选项，但是EhSyringe无法响应“确认移动”按钮

**相关网址**
e-hentai.org/mytags
**截图**
启用插件：
![image](https://github.com/EhTagTranslation/EhSyringe/assets/52618207/071951dd-ed9a-4ea1-89f9-1e80e8d718a0)
实际按钮其实已经变成了 Confirm Move
![image](https://github.com/EhTagTranslation/EhSyringe/assets/52618207/ca7272b5-e660-41b0-8921-e3409c152e4b)

**环境**

-   系统: Windows
-   浏览器 Chrome
-   插件版本 2.12.8

**Comment by xb2016** [comment]
https://github.com/EhTagTranslation/EhSyringe/commit/3d71546f4a621ddbe4f8e02acfcc52c898ae6cf5 导致
