### ISSUE TITLE
可以增加一个对标签翻译后增加的小图标的开关吗？

### ISSUE THREAD

**Issue by zerona2018** [EhTagTranslation/EhSyringe#1254]
那个有时候太明显了。单纯字的话不会那么醒目。

**Comment by OpportunityLiu** [comment]
早有了啊

**Comment by OpportunityLiu** [comment]
![image](https://github.com/EhTagTranslation/EhSyringe/assets/13471233/0e97af5e-7b68-476f-a548-b1fd355cc232)
