### ISSUE TITLE
请问这个aip调用次数超过限制是咋回事

### ISSUE THREAD

**Issue by gewuagewua** [EhTagTranslation/EhSyringe#1255]
**描述问题**
不能检查更新
**相关网址**

**截图**
<img src="https://img.chkaja.com/ecdf40644294eaf8.png" alt="ecdf40644294eaf8.png" title="ecdf40644294eaf8.png" />
**环境**

-   系统: [例如: Windows Android]
- win11
-   浏览器 [例如: Chrome Firefox]
- edge
-   插件版本 [例如: 1.0.0]
- 2.12.11 版本

**Comment by OpportunityLiu** [comment]
公共代理超限了吧，换个节点

**Comment by OpportunityLiu** [comment]
fixed in 63a2b4771768561585d1c9ab4b69ff619fc7c028

**Comment by Mapaler** [comment]
使用代理应该是用户自身的问题，换成某个固定代理，那这个代理坏了怎么办呢？

**Comment by OpportunityLiu** [comment]
> 使用代理应该是用户自身的问题，换成某个固定代理，那这个代理坏了怎么办呢？

坏了就不用更新翻译了呗
