### ISSUE TITLE
請問可以同時雙標籤搜尋嗎?

### ISSUE THREAD

**Issue by leadra** [EhTagTranslation/EhSyringe#1259]
"漢語"+"作者名"，點選兩個，然後可以直接找包含兩個標籤的漫畫

**Comment by OpportunityLiu** [comment]
你是问在哪里的操作？

这个项目只是汉化，添加的功能只有标签搜索提示，剩下的 E 站本来有啥就是啥样的，你是不是应该去 E 站的论坛问？

**Comment by leadra** [comment]
是想要能夠點畫廊的標籤來進行搜索，一般來說只能
![image](https://github.com/EhTagTranslation/EhSyringe/assets/67009996/e7a682a1-ae3e-4d1f-a4d8-934bd60a10b7)
點一個TAG來搜索，想說能不能同時讀取2個TAG後搜索

**Comment by OpportunityLiu** [comment]
去找 tenboro 吧。。。这跟我们有啥关系
