### ISSUE TITLE
其他地方成功翻译，但是标签不显示翻译

### ISSUE THREAD

**Issue by zhiheng13** [EhTagTranslation/EhSyringe#1262]
**描述问题**标签不显示翻译

**相关网址**e站和eh都测试了都不显示

**截图**
![QQ截图20240806155256](https://github.com/user-attachments/assets/9ce19629-1c8d-42e7-9663-c90537d913c6)

**环境**

-   系统: windows
-   浏览器 Chrome 版本 127.0.6533.89（正式版本） （64 位）
-   插件版本 3.0.5

**Comment by OpportunityLiu** [comment]
1. 确认一下已经成功加载标签翻译数据
    ![image](https://github.com/user-attachments/assets/abc2b6d0-89d3-4e9d-9706-96e253055d96)
2. 确认设置里已经打开标签翻译
    ![image](https://github.com/user-attachments/assets/4679e912-3d07-42c4-810c-d89656b8cf8d)
3. 如果都没问题，贴一下 F12 控制台日志

**Comment by zhiheng13** [comment]
感谢您的回复。
之前没有显示标签的时候我检查了这个设置小图标，里面所有的选项都勾选上了包括翻译标签。
然后因为不能翻译标签我就暂时把插件关闭了。
刚刚收到您的回复，我就重新打开插件准备重新检查一下情况，然后截一下F12日志。
重新打开插件后，点开这个设置小图标完成了一次自动更新，然后标签翻译就生效了。
再次感谢您的回复，问题已经解决了。
