### ISSUE TITLE
v1.2.9版无法翻译标签

### ISSUE THREAD

**Issue by sorakirahk** [EhTagTranslation/EhSyringe#144]
- 系统: [例如: Windows7]
 - 浏览器 [Cent Browser 版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)]
 - 插件版本 [v1.2.9]

之前使用v1.2.8版一切正常
看到1.2.9支持了收藏搜索和添加标签的标签自动完成，就更新了下

除了和标签相关的，其余插件功能一切正常

首页my tag无法翻译标签
![sora_2020-05-08_11-44-32](https://user-images.githubusercontent.com/24854146/81368028-5be67680-9121-11ea-84ec-51e61dd4425b.jpg)

详情页tag无法翻译标签
![sora_2020-05-08_11-32-00](https://user-images.githubusercontent.com/24854146/81367466-e8903500-911f-11ea-8f8d-b75bb4dcc236.jpg)

不知道是哪里有问题导致标签描述显示不完整
![sora_2020-05-08_11-38-43](https://user-images.githubusercontent.com/24854146/81367766-a87d8200-9120-11ea-95a5-a0ab00d43ced.jpg)

换回1.2.8版后除了标签描述显示不完整外其余功能正常

**Comment by OpportunityLiu** [comment]
标签翻译的那个问题修好了

标签描述应该是你浏览器样式的问题，有装别的插件吗？我这里几个浏览器都没有这个问题

**Comment by sorakirahk** [comment]
> 标签翻译的那个问题修好了
> 
> 标签描述应该是你浏览器样式的问题，有装别的插件吗？我这里几个浏览器都没有这个问题

感谢
标签描述不完全问题经过逐一排查插件，发现是 github.com/dnsev-h/x 中的 Gallery Metadata 脚本导致的，禁用后就正常了
