### ISSUE TITLE
v1.2.10单击标签没有显示标签介绍

### ISSUE THREAD

**Issue by MelloJyoutoji** [EhTagTranslation/EhSyringe#169]
**描述问题**
单击标签在右边没有标签介绍的显示, 今天出现的, 昨天还是正常. 
可能是我这边的问题但我不知道怎么解决, 请帮助我, 谢谢! 

顺带一提, 在Google里有这个错误, 请见图二
**相关网址**
exhentai
**截图**
![{B9807843-D7F0-478D-B140-2A470427411A} png](https://user-images.githubusercontent.com/48471970/82911779-e262db00-9f9e-11ea-8524-26eb06b1f7b2.jpg)

![{D9B58B52-60B0-44D1-A3C4-087C8E85EB26} png](https://user-images.githubusercontent.com/48471970/82912490-c3187d80-9f9f-11ea-8c8d-ab5c1f6c0b1c.jpg)

**环境**

-   系统: [windows10]
-   浏览器 [Chrome 83.0.4103.61]
-   插件版本 [1.2.8, 1.2.9, 1.2.10] 均有问题

**Comment by xioxin** [comment]
已修复, @Mapaler 麻烦发布一些

**Comment by xioxin** [comment]
图二 是一个安全警告,因为在https的页面中插入了http的图片.

**Comment by Mapaler** [comment]
发布得叫 @OpportunityLiu 来啊，这个项目我根本就看不懂的

**Comment by OpportunityLiu** [comment]
git tag v1.2.11
git push --tags
就自动发布了

**Comment by OpportunityLiu** [comment]
当然发之前记得把package.json里版本先改了

**Comment by MelloJyoutoji** [comment]
好的, 谢谢你们

**Comment by xioxin** [comment]
> 发布得叫 @OpportunityLiu 来啊，这个项目我根本就看不懂的

at错了 😂

**Comment by xioxin** [comment]
> git tag v1.2.11
> git push --tags
> 就自动发布了

好的不过我到晚上才有时间

**Comment by OpportunityLiu** [comment]
@xioxin 我弄好了
