### ISSUE TITLE
违反chorme网上商店规则求解

### ISSUE THREAD

**Issue by lawill12138** [EhTagTranslation/EhSyringe#18]
**描述问题**
晚上照例打开ex发现回到英文界面，心想我中文针呢，扩展栏也没看见。点进chorme扩展程序管理发现被chorme停了。虽然不知道发生了什么，我先放一个举报者的emoji在这里.jpg

**相关网址**

**截图**
![QQ图片20190915002402](https://user-images.githubusercontent.com/49589013/64911004-2a163f00-d74f-11e9-9272-154c61e20a40.png)

**环境**
 - 系统: [例如: Windows Android]
 - 浏览器 [例如: Chrome Firefox]
 - 插件版本 [例如: 1.0.0]

**Comment by Mapaler** [comment]
火狐的插件还在

**Comment by WANGCHIENCHIH** [comment]
crx版本安裝後也會通報違反規則

**Comment by OpportunityLiu** [comment]
#10 请集中到这边讨论吧，这个 issue 就先关闭了。
