### ISSUE TITLE
希望能够点击标签之后快捷关注

### ISSUE THREAD

**Issue by 1235789gzy1** [EhTagTranslation/EhSyringe#211]
ex有关注标签的功能，希望能够通过这个插件快捷的将标签添加到 “我的标签” 中

**Comment by xioxin** [comment]
关注标签不是高频操作, 并且还有颜色、权重之类的设置.
替代方案是给标签管理输入框增加输入提示的能力. 像搜索一样

**Comment by OpportunityLiu** [comment]
> 关注标签不是高频操作, 并且还有颜色、权重之类的设置.
> 替代方案是给标签管理输入框增加输入提示的能力. 像搜索一样

那个框自带提示，ehtt.now.sh用的就是这个API

**Comment by xioxin** [comment]
> > 关注标签不是高频操作, 并且还有颜色、权重之类的设置.
> > 替代方案是给标签管理输入框增加输入提示的能力. 像搜索一样
> 
> 那个框自带提示，ehtt.now.sh用的就是这个API

原来如此, 之前都没发现, 大概是我网太卡了

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/88270218-de85d780-cd07-11ea-9670-6f5573f93979.png)
只有他知道标签的master-slave状态

**Comment by OpportunityLiu** [comment]
倒是可以考虑反过来把这个api用来搞搜索的自动完成
![图片](https://user-images.githubusercontent.com/13471233/88270539-61a72d80-cd08-11ea-9001-30df0642b33b.png)

尤其是现在作品名字越来越长

**Comment by xioxin** [comment]
厉害了
