### ISSUE TITLE
无法获取版本更新

### ISSUE THREAD

**Issue by SekiBetu** [EhTagTranslation/EhSyringe#214]
**描述问题**
无法获取版本更新，点进TAG版本网址后发现是page not found
**相关网址**
https://github.com/EhTagTranslation/Database/releases/tag/v-13d5fe8a37ff08ea1dcadec6acc0c18c1d840031
**截图**
![image](https://user-images.githubusercontent.com/38283893/87164275-2c0f4700-c2fb-11ea-803b-e52247220a22.png)
**环境**

-   系统: WIN10 19041.329
-   浏览器 Chrome 83.0.4103.116
-   插件版本 1.3.1

**Comment by SekiBetu** [comment]
刚才右下角不停弹未知的更新检查通知，过了一段时间，现在又好了，又能更新了，可能是我网络问题？

**Comment by OpportunityLiu** [comment]
嗯，完了我把错误提示优化下
