### ISSUE TITLE
User script 支持

### ISSUE THREAD

**Issue by OpportunityLiu** [EhTagTranslation/EhSyringe#226]
现在这个上不了架太难受了

看了一下，应该稍微改改就能用webpack打包一个user script

那个是不是上架没啥要求的

@xioxin @Mapaler

**Comment by Mapaler** [comment]
那个脚本网有专门的成人flag，勾上后要么用户打开成人浏览开关，要么直接用成人域名访问

**Comment by Mapaler** [comment]
而且就算不上那个网站，直接从Github安装Tampermonkey也可以更新的

**Comment by xioxin** [comment]
之前遇到一个问题是 tampermonkey 不能确保脚本在body加载前注入到页面中.
会导致偶尔页面不翻译,或者是网页的一部分没有翻译.
之前解决办法是遍历一遍已有的dom可以解决. 加载效果就是偶尔显示英文再变成中文.

后来尝试插件发现没有这个问题,并且还有更多高级的功能就选择了插件.
然后插件就被和谐了. 哎

**Comment by OpportunityLiu** [comment]
@Mapaler 已经初步可以用了，设置界面还没做

![图片](https://user-images.githubusercontent.com/13471233/88083346-8343d000-cbb5-11ea-8917-901c10035786.png)
可能需要把这个勾上

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/88084328-d23e3500-cbb6-11ea-9232-d2b3a061c0c1.png)
最好也关了, 我这里不关浏览器直接卡死

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/88136350-9c7f6780-cc1b-11ea-985e-6451bf11fc8c.png)

需要撸eh和ex的对应样式

**Comment by xioxin** [comment]
可以使用 Shadow DOM 隔离页面和设置面板的样式

**Comment by OpportunityLiu** [comment]
> 可以使用 Shadow DOM 隔离页面和设置面板的样式

不管是否隔离，都应该重新做一下样式，这个白底在里站很难看啊

**Comment by OpportunityLiu** [comment]
> 最好关了, 我这里不关浏览器直接卡死, 脚本太大

![图片](https://user-images.githubusercontent.com/13471233/88140410-44992e80-cc24-11ea-8978-982d408b5c7e.png)
加了个调试用的脚本

**Comment by Mapaler** [comment]
Shadow DOM 又是什么新技术

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/88151036-c1340900-cc34-11ea-8f99-e6ed6320125d.png)
用了CDN以后已经看不到那个漂亮的动画了

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/88166579-0dd60f00-cc4a-11ea-9bd1-87c5de090705.png)

**Comment by OpportunityLiu** [comment]
@xioxin @Mapaler 

 测测alpha7没啥问题可以发了

**Comment by Mapaler** [comment]
一觉醒来都已经Alpha10了

**Comment by OpportunityLiu** [comment]
都有试过吗？

**Comment by Mapaler** [comment]
刚才才第一次看，里面为什么那么多层
如果下面是引用库的话，可以用require吧，内置看起来乱乱的。

**Comment by Mapaler** [comment]
用起来目前没发现体验差异，牛逼

**Comment by OpportunityLiu** [comment]
发布了
https://greasyfork.org/zh-CN/scripts/407833-ehsyringe

**Comment by Mapaler** [comment]
介绍怎么把这边的Readme全搬过去了，不需要扩展的安装方法吧

**Comment by OpportunityLiu** [comment]
> 介绍怎么把这边的Readme全搬过去了，不需要扩展的安装方法吧

自动同步的，如果你有闲情逸致维护两份说明可以去改，已经在那面添加你和 @xioxin 为管理了

**Comment by OpportunityLiu** [comment]
https://www.level-plus.net/read.php?tid-898541.html

**Comment by Mapaler** [comment]
没有账号看不了的

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/88816673-397b6b00-d1ef-11ea-8744-3367023fa7fb.png)
