### ISSUE TITLE
选

### ISSUE THREAD

**Issue by silver-gun** [EhTagTranslation/EhSyringe#233]
**描述问题**

**相关网址**

**截图**

**环境**

-   系统: [例如: Windows Android]
-   浏览器 [例如: Chrome Firefox]
-   插件版本 [例如: 1.0.0]

**Comment by OpportunityLiu** [comment]
啥系统啥版本啊？

**Comment by silver-gun** [comment]
解决了，我刚刚点错文件夹了，抱歉
