### ISSUE TITLE
v2.0.3 error

### ISSUE THREAD

**Issue by sorakirahk** [EhTagTranslation/EhSyringe#241]
今天更新了2.0.3版后无法使用，直接报错

![sora_2020-07-30_09-29-04](https://user-images.githubusercontent.com/24854146/88870126-28f6df00-d247-11ea-892d-084335eae14b.jpg)

```
💉 插件 加载失败

上下文

_generated_background_page.html
堆叠追踪
script/background.js:1 (匿名函数)
script/vendor.js:31 (s)
```

-   浏览器 [Cent Browser版本 4.2.10.171（正式版本） （64 位） (portable) (Chromium 80.0.3987.163)]
-   插件版本 [2.0.3]

**Comment by OpportunityLiu** [comment]
cdn出问题了，等下试试吧。。。

**Comment by OpportunityLiu** [comment]
https://github.com/EhTagTranslation/EhSyringe/blob/8a24c6f0ce8942bb4cfc3723c978bf047a29cb69/src/services/database.ts#L22-L27

加了几个备用地址，要是都出问题那就真没办法了
