### ISSUE TITLE
2.0.x版在waterfox classic 2020.7 x64上无法使用了

### ISSUE THREAD

**Issue by nomosaic** [EhTagTranslation/EhSyringe#243]
Win7SP1 x64系统，2.0.x版在Waterfox Classic 2020.7 x64上彻底无法使用了，Tag版本N/A，更新检查失败

**Comment by OpportunityLiu** [comment]
我猜和这个 #241 是一个问题，有试过2.0.4吗？

**Comment by nomosaic** [comment]
> 
> 
> 我猜和这个 #241 是一个问题，有试过2.0.4吗？

现在更新到2.0.5，也一样，
tag版本：N/A
上次更新：N/A
更新检查：获取失败

**Comment by OpportunityLiu** [comment]
试下 2.0.6？

**Comment by nomosaic** [comment]
> 
> 
> 试下 2.0.6？

重启之后，可以了
