### ISSUE TITLE
是关于E绅士翻译注射器1.3.14的

### ISSUE THREAD

**Issue by oldmanM-cn** [EhTagTranslation/EhSyringe#278]
**描述问题**
非常清楚插件已经不再更新了。就是之前数据还能在页面正常更新，是否文件位置变化而不能更新，有恢复的可能否？
**相关网址**

**截图**
![捕获](https://user-images.githubusercontent.com/55091373/91972070-be0c5c80-ed4c-11ea-8eb4-f898a0fbed5e.PNG)

**环境**

-   系统: Windows 
-   浏览器 :  Firefox
-   插件版本 1.3.14

**Comment by OpportunityLiu** [comment]
所以新版本有啥缺陷，非要用之前的版本？

**Comment by oldmanM-cn** [comment]
> 
> 
> 所以新版本有啥缺陷，非要用之前的版本？

也不是说有缺陷啦，新版本的tag介绍是要点了之后，然后显示在旁边的框嘛，这点习惯了老的这个方便，移上去就在上面显示了。如果是确定老的这个没得恢复的，那也会用新版本的。总之很感谢回复。

**Comment by OpportunityLiu** [comment]
@xioxin 有空看下吧

**Comment by Mapaler** [comment]
给新版本增加一种传统的显示模式更合适还是修旧的让可以继续使用更合适？

**Comment by oldmanM-cn** [comment]
> 
> 
> 给新版本增加一种传统的显示模式更合适还是修旧的让可以继续使用更合适？

任意一种都可以，但是印象是旧版不更新了。总之非常感谢。

**Comment by Mapaler** [comment]
之前的问题应该是Github改版，导致版本信息获取的位置变化了，我简单修改了一下似乎能用了。
因为我没有 EhTagSyringe 的 GreasyFork 更新权限，所以你只能自己去github上装。
当然还是建议直接用新版EhSyringe。

**Comment by oldmanM-cn** [comment]
> 之前的问题应该是Github改版，导致版本信息获取的位置变化了，我简单修改了一下似乎能用了。
> 因为我没有 EhTagSyringe 的 GreasyFork 更新权限，所以你只能自己去github上装。
> 当然还是建议直接用新版EhSyringe。

非常感谢更新，但是问题貌似还严重了。现在插件整个没效果，虽然油猴显示开了 OTL

**Comment by Mapaler** [comment]
你是在哪里更新的，我是在数据库页面更新后可以正常使用

**Comment by Mapaler** [comment]
应该是你是重新安装的，所以在E站看不到菜单。我刚才简单解决了这个问题。

**Comment by oldmanM-cn** [comment]
> 
> 应该是你是重新安装的，所以在E站看不到菜单。我刚才简单解决了这个问题。

是的，因为前面你说要去GitHub装过，现在问题彻底解决了，真的很谢谢你。
