### ISSUE TITLE
标签图标无法显示

### ISSUE THREAD

**Issue by XESA2333** [EhTagTranslation/EhSyringe#295]
**描述问题**
刚更新了一下浏览器版本，重启后发现有的标签图标无法显示
**相关网址**
https://e-hentai.org/mytags  其他显示标签的地方
**截图**
![捕 获](https://user-images.githubusercontent.com/68879118/93305431-16edf180-f831-11ea-9ef9-9c60d685fa43.JPG)

**环境**

-   系统:  Windows 10-1909
-   浏览器 Chrome 85.0.4183.102（64 位）
-   插件版本 2.0.7

**Comment by XESA2333** [comment]
额，我用edge试了一下，标签图标是正常的。。。难不成是浏览器的问题

**Comment by XESA2333** [comment]
目前我看到除了上面截图的外，还有扶她\水手服\过膝袜\裤袜\百合标签图标无法显示

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/93407292-5fa2ba80-f8c4-11ea-818a-eb5834c0a7d6.png)

原因就是这个，新浪图床用不下去了，哪天写个脚本把这些图片都转移到其他地方吧

**Comment by XESA2333** [comment]
了解，能解决就好
