### ISSUE TITLE
希望能和Mayriad's EH Master Script共存

### ISSUE THREAD

**Issue by baysonfox** [EhTagTranslation/EhSyringe#304]
插件开启前:
![image](https://user-images.githubusercontent.com/23008133/94700158-c23c9180-036d-11eb-94c4-31e8863f81c8.png)
插件开启后:
![image](https://user-images.githubusercontent.com/23008133/94700047-9faa7880-036d-11eb-8e71-e98b0c8c16e7.png)
用户脚本会在页面内添加额外内容，而插件会直接覆盖,
希望能做到只替换tag和界面部分，不影响部分用户脚本加载.

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/94984179-f2f21600-057b-11eb-9866-0dd812cb12f2.png)
![图片](https://user-images.githubusercontent.com/13471233/94984206-22088780-057c-11eb-9c31-c8b977e6d365.png)

这脚本在用这样的方式找网页中的元素，一汉化他就找不到了。。。

你只能选择把界面汉化关掉

**Comment by baysonfox** [comment]
感谢！
