### ISSUE TITLE
能不能支持一下http://exhentai.est.institute/这个镜像站点

### ISSUE THREAD

**Issue by mugenexus** [EhTagTranslation/EhSyringe#393]
**描述你想要的功能**
被墙了以后只能从这个镜像站进了，但是插件好像不支持这个站点

**Comment by OpportunityLiu** [comment]
目前只是SNI阻断，所以准备做Domain fronting，还用不上代理

**Comment by OpportunityLiu** [comment]
建议用domain fronting直连。。。

**Comment by OpportunityLiu** [comment]
人家自己做了魔改的版本 http://exhentai.est.institute/EhSyringe.user.js
