### ISSUE TITLE
EhSyringe与E-Hentai-Downloader冲突

### ISSUE THREAD

**Issue by oweaF** [EhTagTranslation/EhSyringe#4]
**描述问题**
EhSyringe v1.1.1
E-Hentai-Downloader v1.31.3
开启了注射器，Downloader无法使用，具体表现为点击Download Archive按钮无反应

**相关网址**
[https://github.com/ccloli/E-Hentai-Downloader](url)

**环境**
 - 系统：Windows
 - 浏览器：Chrome
 - 插件版本：1.1.1

**Comment by xioxin** [comment]
问题已处理, 1.1.2版本会修复这个问题, 这两天会发布这个版本

**Comment by xioxin** [comment]
1.1.2 已发布
