### ISSUE TITLE
关于<翻译界面>选项打开后时间显示错误的问题

### ISSUE THREAD

**Issue by szbiao218** [EhTagTranslation/EhSyringe#409]
您好，我发现一个关于时间显示的问题，不知是否为个例。
在打开<翻译界面>功能前，日期显示为：<Posted: | 2021-02-20 08:20>
在打开此功能后，日期会变为：<发布于: | 2/2016:20>
这是其中一例，其他的也会显示错误的日期。

-   浏览器: Chrome 88.0.4324.182(正式版本)(64 位)
-   插件版本 : v2.0.8

**Comment by OpportunityLiu** [comment]
这是feature
