### ISSUE TITLE
Firefox 下架

### ISSUE THREAD

**Issue by SettingDust** [EhTagTranslation/EhSyringe#43]
**描述问题**
Firefox addon 下架

**相关网址**
https://addons.mozilla.org/zh-CN/firefox/addon/ehsyringe/

**Comment by Mapaler** [comment]
有人举报了吗？:sweat_smile:

**Comment by xioxin** [comment]
被退回 作者： Cse 5 days ago

This version didn't pass review because of the following issue:
The features of this extension does not comply with Mozilla’s Acceptable Use Policy (https://www.mozilla.org/about/legal/acceptable-use/).

**Comment by SettingDust** [comment]
> 被退回 作者： Cse 5 days ago
> 
> This version didn't pass review because of the following issue:
> The features of this extension does not comply with Mozilla’s Acceptable Use Policy ([mozilla.org/about/legal/acceptable-use](https://www.mozilla.org/about/legal/acceptable-use/)).

搞个点击七次版本号之类的东西?

**Comment by OpportunityLiu** [comment]
没办法，跟chrome一样sideload吧。。

**Comment by Mapaler** [comment]
手机上咋办？

**Comment by Mapaler** [comment]
有没有改编成脚本的可能？

**Comment by xioxin** [comment]
翻译原理上是可以改的，一些额外的功能可能会没有， 并且体验可能没有之前好了

**Comment by Mapaler** [comment]
地址栏的额外功能这些使用几率高吗？

**Comment by xioxin** [comment]
之前还有个问题是不能严格的吧代码家在到dom加载之前，导致翻译失败。
不知道现在这个bug修没修复。

**Comment by OpportunityLiu** [comment]
> 有没有改编成脚本的可能？

所以当初转成插件是为了啥？

**Comment by Mapaler** [comment]
那这么人畜无害的插件为什么不准通过？

**Comment by RealXuChe** [comment]
到底是哪里触犯了火狐的使用策略？Mozilla也是审核太过了。之前IDM 插件也不知为何被拉了黑名单.....

**Comment by avviz** [comment]
> 被退回 作者： Cse 5 days ago
> 
> This version didn't pass review because of the following issue:
> The features of this extension does not comply with Mozilla’s Acceptable Use Policy (https://www.mozilla.org/about/legal/acceptable-use/).

“上传、下载、传播、展示或授权访问包含性或暴力图形描述的内容”
也许和缩略图有关

**Comment by RealXuChe** [comment]
可以让插件默认不附带翻译数据库的链接和翻译数据库，而是让用户在安装后手工填入翻译数据库的链接并下载翻译数据库。这样应该就可以规避审核政策了。

**Comment by OpportunityLiu** [comment]
> 没办法，跟chrome一样sideload吧。。

firefox 的 sideload 还是非持久化的，真的没法用了

**Comment by OpportunityLiu** [comment]
需要用的话还是装开发者版吧

**Comment by linonetwo** [comment]
我也推荐用 Chrome 版的，如果日常用 Firefox，用常用浏览器逛 EH 会污染浏览历史记录，让它变得不纯洁惹

**Comment by Mapaler** [comment]
你可以用隐私模式浏览啊

**Comment by linonetwo** [comment]
隐私模式要每次重新登录吧

**Comment by Aloxaf** [comment]
话说即使被下架了，也可以手动签名吧？只要不通过 AMO 分发就行了。

**Comment by OpportunityLiu** [comment]
签不了，直接401

**Comment by Aloxaf** [comment]
可能 ID 被拉黑了？
换一个 ID 呢？

我试了下签成功了，能在稳定版上安装：
[ehsyringe-1.2.13-an+fx.zip](https://github.com/EhTagTranslation/EhSyringe/files/4790065/ehsyringe-1.2.13-an%2Bfx.zip)

**Comment by OpportunityLiu** [comment]
能签名就有ID，有ID就能举报，举报就会被BAN，没有任何意义

**Comment by OpportunityLiu** [comment]
跟FF和举报者斗智斗勇，没那个闲工夫

**Comment by Aloxaf** [comment]
哎，这个世界太乱……
