### ISSUE TITLE
【计划】设置面板

### ISSUE THREAD

**Issue by xioxin** [EhTagTranslation/EhSyringe#5]
增加设置面板：
* [x] 禁用UI翻译
* [x] 禁用TAG翻译
* [x] 介绍图片过滤等级 （不显示，NSFW，R18，R18G）
* [x] tag介绍
* [x] 自动补全
* [x] 自动更新
* [x] 设置面板UI
* [x] 测试Chrome
* [x] 测试Firefox
* [x] 测试Android

**Comment by Mapaler** [comment]
我觉得有两处吧，一个是扩展选项的面板，用来设置少改的和复杂的设置；
![Screenshot_2019-08-12-12-16-28](https://user-images.githubusercontent.com/6565860/62845499-1f552e00-bcfb-11e9-831c-edc6755b2193.png)
另一个是扩展图标点出来的快捷操作layer，只控制快速切换功能。
![Screenshot_2019-08-12-12-16-45](https://user-images.githubusercontent.com/6565860/62845500-1f552e00-bcfb-11e9-96bb-d7d14382a1ed.png)
如果进一步做的话，其实可以把Editer内置。
![Screenshot_2019-08-12-12-17-00](https://user-images.githubusercontent.com/6565860/62845506-254b0f00-bcfb-11e9-882c-7163a7c2e9f1.png)

**Comment by OpportunityLiu** [comment]
>     * 介绍图片过滤等级 （全部显示，仅NSFW，全部过滤）

已经把 R18 和 R18G 的支持加上了
https://github.com/EhTagTranslation/EhSyringe/blob/086e22ccc89d1c285c8c4fa5fde5a48aed5dc264/src/tool/tool.ts#L10-L15

**Comment by xioxin** [comment]
并不会内置编辑器。
可配置项不多，应该不会用设置面板。
现在首选的是在popup页面添加设置面板

**Comment by xioxin** [comment]
大概这个样子
![image](https://user-images.githubusercontent.com/5716100/62846703-b4105980-bd04-11e9-9183-2138730dba84.png)

**Comment by OpportunityLiu** [comment]
就不用写禁用了吧，默认四个都打勾就好了呗

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/62846797-5af4f580-bd05-11e9-87d2-1209981859c7.png)

**Comment by Mapaler** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/13471233/62846797-5af4f580-bd05-11e9-87d2-1209981859c7.png)

我还是觉得slidebar比较好

**Comment by OpportunityLiu** [comment]
> 我还是觉得slidebar比较好，就像安全等级一样。

???我说啥了？

**Comment by Mapaler** [comment]
> 
> 
> > 我还是觉得slidebar比较好，就像安全等级一样。
> 
> ???我说啥了？

我理解错了，因为你下面一条紧接着是分级的图片，我以为你是说图片等级不要写禁用，改成复选框分别控制。

原来是前面的不要写禁用。

**Comment by OpportunityLiu** [comment]
我意思是G、R18、R18G

**Comment by OpportunityLiu** [comment]
只是强迫症，never mind

**Comment by xioxin** [comment]
popup 我还要做一些调整 等我调整好了再修改

**Comment by xioxin** [comment]
现在大概先这样 至少功能已经实现了， 今晚再调整样式

**Comment by OpportunityLiu** [comment]
稍微改了一下

**Comment by xioxin** [comment]
什么时候测试下 准备上架吧

**Comment by OpportunityLiu** [comment]
没啥问题

**Comment by OpportunityLiu** [comment]
设置建议改成自动保存比较好，尤其移动端上，保存按钮的位置在页面底部

**Comment by xioxin** [comment]
> 设置建议改成自动保存比较好，尤其移动端上，保存按钮的位置在页面底部

可以给外框加一个最大高度

**Comment by xioxin** [comment]
没有问题的话我今晚发布

**Comment by OpportunityLiu** [comment]
行，我又改了点，你可以 看下

**Comment by xioxin** [comment]
我有个新的项目，本地的本子管理软件。有没有兴趣

nest.js 后端 angular 前端
主要是扫描本地磁盘整理本子，在线阅读。
联网采集metadata，自动打标签，本子下载等功能；
类似 happypandax 。

前一段时间下载了3T的本子，很难管理

**Comment by xioxin** [comment]
1.2.0 版本已经发布
好累, 暂时不再增加新功能了.
