### ISSUE TITLE
请求增加左下角图标开启关闭，或者调整位置大小的功能Request to add the function of turning on and off the icon in the lower left corner, or adjusting the position size

### ISSUE THREAD

**Issue by bearcloney** [EhTagTranslation/EhSyringe#507]
**描述你想要的功能**
因为我装了eh的阅读类插件，而EhSyringe图标刚刚好挡住全屏按钮，很郁闷希望能解决
Because I installed the eh reading plug-in, and the EhSyringe icon just blocked the full screen button, I was very depressed and hoped to solve it

**Comment by OpportunityLiu** [comment]
released in v 2.4.0
