### ISSUE TITLE
脚本的右下角针筒图标没了

### ISSUE THREAD

**Issue by ChloeKurumi** [EhTagTranslation/EhSyringe#581]
**描述问题**
脚本的右下角针筒图标没了
**相关网址**

**截图**
![image](https://user-images.githubusercontent.com/41937301/128287659-fa02c699-4469-4f95-90a1-b916ff008b45.png)

**环境**

-   系统: [例如: Windows Android] Windows
-   浏览器 [例如: Chrome Firefox] Chrome
-   插件版本 [例如: 1.0.0] 2.5.0

**Comment by OpportunityLiu** [comment]
Fixed in v2.5.1
