### ISSUE TITLE
每次安装完 过不了多久再点扩展程序就提示 无法访问您的文件该文件可能已被移至别处

### ISSUE THREAD

**Issue by ve-Wu** [EhTagTranslation/EhSyringe#590]
**描述问题**
每次安装完 过不了多久再点扩展程序就提示 无法访问您的文件该文件可能已被移至别处

无法访问您的文件该文件可能已被移至别处、修改或删除。
ERR_FILE_NOT_FOUND

**截图**
![QQ截图20210813235002](https://user-images.githubusercontent.com/79002099/129385508-d893c0ed-a71a-455a-b9c0-1d600d9b18b6.jpg)

**Comment by OpportunityLiu** [comment]
我感觉是你没把扩展解压到一个稳定的文件夹位置，被垃圾清理工具删了。

目前还是建议直接用用户脚本。如果你对那几个扩展独占的功能需求不大的话。

**Comment by OpportunityLiu** [comment]
如果还是不行的话就安装 UserScript 版本吧，功能也差不多

**Comment by ve-Wu** [comment]
就很迷  是正常翻译  但就是提示这个
