### ISSUE TITLE
配合 AdGuard Windows 无法使用

### ISSUE THREAD

**Issue by Kawaii-KM** [EhTagTranslation/EhSyringe#597]
**在 AdGuard Windows 中添加 扩展程序 后， exhentai.org 并没有被翻译**

**exhentai.org**

![image.png](https://i.loli.net/2021/08/20/J2xpUQ18mjYDdAz.png)

**环境**

-   系统: Windows 11 21H2 with AdGuard 7.6.1
-   浏览器 Edge 93
-   插件版本 2.5.1

（如有需要可提供AdGuard进行测试

**Comment by OpportunityLiu** [comment]
可以，咋提供呢？

**Comment by Kawaii-KM** [comment]
> 可以，咋提供呢？

Telegram?

**Comment by OpportunityLiu** [comment]
https://t.me/OpportunityLiu

**Comment by OpportunityLiu** [comment]
Fixed in 2.5.2
