### ISSUE TITLE
TypeError: this.tagList.next is not a function

### ISSUE THREAD

**Issue by xioxin** [EhTagTranslation/EhSyringe#6]
@Mapaler 

![image](https://user-images.githubusercontent.com/5716100/63263816-28766a00-c2bc-11e9-9d74-6abf17016875.png)

![image](https://user-images.githubusercontent.com/5716100/63263900-58be0880-c2bc-11e9-905c-f5e583904e35.png)

**Comment by xioxin** [comment]
我并不是很理解错误是怎么产生的 我发现我安装了两遍插件, 卸载掉一个就回复正常了, 可是这两个不应该是独立的吗

**Comment by xioxin** [comment]
暂时 close

**Comment by OpportunityLiu** [comment]
之前有改成过用observer，后面应该revert了
