### ISSUE TITLE
希望 E-Hentai 中的 Hentai@Home 页面能被翻译

### ISSUE THREAD

**Issue by Matcha-sama** [EhTagTranslation/EhSyringe#604]
如题
（因为我也是H@H用户

**Comment by Kawaii-KM** [comment]
同一页面出现两次以上的单词是否需要重复翻译

**Comment by OpportunityLiu** [comment]
不用

**Comment by Matcha-sama** [comment]
对于需要调换顺序，但带有超链接的句子
![image](https://user-images.githubusercontent.com/56059155/131219264-24740b01-0afc-4c6b-9bda-b62deabaf6e9.png)
我想翻译成 
[联系 Tenboro](https://forums.e-hentai.org/index.php?act=Msg&CODE=4&MID=6) 以添加更多客户端
应该如何翻译

**Comment by OpportunityLiu** [comment]
没治，只能写成 要添加更多客户端，请联系

**Comment by Matcha-sama** [comment]
![image](https://user-images.githubusercontent.com/56059155/132020689-0a8e6f3a-8363-4341-82ff-14d7b8d8f323.png)
咦，为什么长句都没有被翻译

**Comment by OpportunityLiu** [comment]
我周末看下吧，估计空格啥的没对上

**Comment by OpportunityLiu** [comment]
改好了
