### ISSUE TITLE
加载脚本后，搜索框尺寸变小

### ISSUE THREAD

**Issue by lazureice** [EhTagTranslation/EhSyringe#616]
**描述问题**
加载脚本后，搜索框尺寸变小。chrome 扩展是没有问题的，只有使用脚本才有这个问题。

**截图**
加载脚本前：
![image](https://user-images.githubusercontent.com/12579737/131777406-9abc1da2-4558-4d40-8371-17dc8f32ebc8.png)

加载脚本后：
![image](https://user-images.githubusercontent.com/12579737/131777383-fd1759ef-8c50-4210-8ec4-619b73bef68c.png)

使用插件：
![image](https://user-images.githubusercontent.com/12579737/131777931-9557ecb3-a05b-4af5-b43f-34a59250c778.png)

**环境**

-   系统: Windows
-   浏览器: Chrome
-   插件版本: 2.5.3
-   脚本管理器: Tampermonkey

**Comment by OpportunityLiu** [comment]
Fixed in 2.5.5
