### ISSUE TITLE
捐赠的消费历史金额显示错误

### ISSUE THREAD

**Issue by simonkimi** [EhTagTranslation/EhSyringe#654]
**描述问题**
捐赠金额全部变成1美元
**相关网址**
https://e-hentai.org/bitcoin.php?coin=BTC
**截图**
![图片](https://user-images.githubusercontent.com/49084387/134506669-d0f5cb7a-7e45-4dc3-9005-589f390bf120.png)
![图片](https://user-images.githubusercontent.com/49084387/134506716-8d328e22-a623-4d38-b0c0-0e65e4aa57b9.png)

**环境**

-   系统: Windows10 
-   浏览器: Firefox Developer Edition 93.0b8 
-   插件: 油猴 EhSyringe 2.5.6

**Comment by xioxin** [comment]
正则替换写的有点问题，这就改一下
