### ISSUE TITLE
数据库更新出错

### ISSUE THREAD

**Issue by sorakirahk** [EhTagTranslation/EhSyringe#7]
**描述问题**
数据库更新出错

**截图**
![Sora_2019-08-24_10-21-45](https://user-images.githubusercontent.com/24854146/63631378-1b110500-c659-11e9-9dad-b1e6692c4b77.jpg)

**环境**
 - 浏览器 [Chromium 74.0.3729.169]
 - 插件版本 [1.2.0]

**Comment by sorakirahk** [comment]
尴了，才看见commit上修复了 this.tagList.next is not a function
重新安装插件以后就没问题了

**Comment by OpportunityLiu** [comment]
重新安装并不能解决问题，新版还没发布

**Comment by sorakirahk** [comment]
> 重新安装并不能解决问题，新版还没发布

了解，等新版

**Comment by OpportunityLiu** [comment]
1.2.1已经发布
