### ISSUE TITLE
关于日期时间格式

### ISSUE THREAD

**Issue by xjxyv** [EhTagTranslation/EhSyringe#724]
能否增加一个显示原始时间的选项。
经常用EH-Dl下本收藏，在保存的info里用原来的时间好点![屏幕截图 2021-11-20 054017](https://user-images.githubusercontent.com/94707100/142696143-904eaed3-2d76-4caf-aea5-c86658a151f2.png)

**Comment by OpportunityLiu** [comment]
Added in 2.7.0

![image](https://user-images.githubusercontent.com/13471233/142730428-dbbba5a6-8d13-4846-8807-1f26a55c2026.png)
