### ISSUE TITLE
标签空间中的“其他”与“混合”中的标签不显示翻译

### ISSUE THREAD

**Issue by Nigel-NI** [EhTagTranslation/EhSyringe#743]
**描述问题**
标签空间中的“其他”与“混合”中的标签不显示翻译，其他标签空间的标签不受影响
**相关网址**
例如https://e-hentai.org/g/2077907/548ed2af62/
**截图**
![image](https://user-images.githubusercontent.com/23294384/144730987-59f692e6-5af1-484b-bfa4-8b1e05e0bcc7.png)
**环境**

-   系统: windows 10
-   浏览器 chrome
-   插件版本 2.8.1

**Comment by OpportunityLiu** [comment]
你在数据库随便提交点啥然后更新一下翻译就好了。

懒得再改了
