### ISSUE TITLE
顺便也翻译它的设置

### ISSUE THREAD

**Issue by tch1121** [EhTagTranslation/EhSyringe#768]
https://github.com/ccloli/E-Hentai-Downloader

**Comment by xioxin** [comment]
欢迎PR

画廊详情页UI翻译 https://github.com/EhTagTranslation/EhSyringe/blob/master/src/services/ui-translation/data/gallery.ts

**Comment by OpportunityLiu** [comment]
我感觉这么搞会炸的。。 

为啥不去那面请求i18n呢，作者不也是国人

**Comment by tch1121** [comment]
实际上已经翻译到了
我才有了这个想法
![image](https://user-images.githubusercontent.com/89089119/148109853-d9772a81-934b-4606-bc33-f618ab7e2a85.png)

**Comment by xioxin** [comment]
因为"设置"这个翻译e站页面上也有，正好匹配上了 😂
