### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by SekiBetu** [EhTagTranslation/EhSyringe#813]
**描述问题**
Manifest version 2 is deprecated, and support will be removed in 2023.
See https://developer.chrome.com/blog/mv2-transition for more details.
**相关网址**
https://developer.chrome.com/blog/mv2-transition
**截图**
![image](https://user-images.githubusercontent.com/38283893/181721229-ecf78906-896e-4049-9c6b-6f23f678cc69.png)
**环境**

-   系统: Windows
-   浏览器 Chrome
-   插件版本 2.8.10

**Comment by OpportunityLiu** [comment]
Links for FF:
https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/
https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
