### ISSUE TITLE
存档下载页面的翻译

### ISSUE THREAD

**Issue by Kagura-Nanaa** [EhTagTranslation/EhSyringe#819]
**相关页面**
https://plprhexcngkbxoopaqlx.hath.network/archive/1816353/6d3e595ba88014eaffc71d23f55c95bcf83de2ad/uc1i5r59t30/2

**原文**
The file was successfully prepared, and is ready for download.
Click Here To Start Downloading
You can also copy this link to a download manager.

You can also copy this link to a download manager.

**翻译**
该文件已成功准备就绪，可供下载。
点击这里开始下载
你也可以把这个链接复制到下载管理器中。

**Comment by OpportunityLiu** [comment]
Added in v2.8.6
