### ISSUE TITLE
安装扩展后，有报错：Unrecognized manifest key 'applications'

### ISSUE THREAD

**Issue by ChloeKurumi** [EhTagTranslation/EhSyringe#84]
**描述问题**
安装扩展后，有报错
Unrecognized manifest key 'applications'.
"applications":{"gecko":{"id":"{759d5566-1dce-41ae-bae9-00dd5172c422}","strict_min_version":"57.0"}}
**相关网址**

**截图**

**环境**
 - 系统:  Windows
 - 浏览器 Chrome
 - 插件版本 1.2.6

**Comment by OpportunityLiu** [comment]
你的chrome版本是多少？这里80.0.361.57复现不了

**Comment by OpportunityLiu** [comment]
应该只是个warning吧

**Comment by OpportunityLiu** [comment]
1.2.7 分成两个版本了，应该就没这个问题了
