### ISSUE TITLE
无法更新数据，无法获取下载地址，顶多能检测到有新版本

### ISSUE THREAD

**Issue by nomosaic** [EhTagTranslation/EhSyringe#85]
win7 Waterfox Classic x64
如图所示，点击更新之后就显示“无法获取下载地址”
![EhSyringe：无法获取下载地址](https://user-images.githubusercontent.com/14254798/75543575-13de1000-5a5d-11ea-8d16-7d90b58ba6e2.jpg)

**Comment by ee092884** [comment]
我是還在1.2.5就遇到這樣的問題
想說更新到1.2.7 但還是一樣
![image](https://user-images.githubusercontent.com/39590282/75556347-046cc000-5a79-11ea-8541-d25b9ae5d506.png)

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/75578569-06e21080-5a9f-11ea-845d-7b0f9583e2b4.png)

https://github.com/EhTagTranslation/Database 那边的CI出问题了，漏了文件

**Comment by OpportunityLiu** [comment]
1.2.8 应该可以用了，加了一个备用的文件，但是最近github上传文件经常出问题，所以也不一定保证以后更新继续可用。。。目前架构下无解，只能希望GitHub早点修好吧。。。

最近甚至连GitHub爆炸的短信提醒也爆炸了一次。。。

**Comment by Mapaler** [comment]
我还在用1.2.2好像是最后一版架上的

**Comment by nomosaic** [comment]
> 
> 
> 1.2.8 应该可以用了，加了一个备用的文件，但是最近github上传文件经常出问题，所以也不一定保证以后更新继续可用。。。目前架构下无解，只能希望GitHub早点修好吧。。。
> 
> 最近甚至连GitHub爆炸的短信提醒也爆炸了一次。。。

多谢修复，是不是因为用了亚马逊的服务器被挡的缘故？
