### ISSUE TITLE
Fate/Grand Order 的標籤圖標是空白的

### ISSUE THREAD

**Issue by bahamutjr** [EhTagTranslation/EhSyringe#850]
**描述问题**
原作欄目的標籤圖標
大部分作品圖標正常
但是Fate/Grand Order 是個白色方塊
**相关网址**
https://raw.githubusercontent.com/ShuraragiYomiko/ImageforETT/master/NameIcon/fate_grand_order.gif
**截图**
https://i.imgur.com/kPXbvBj.jpg
![image](https://i.imgur.com/kPXbvBj.jpg)
**环境**

-   系统: [例如: Windows Android]
Windows 10 21H2
-   浏览器 [例如: Chrome Firefox]
Microsoft Edge
版本 100.0.1185.50 (官方組建) (64 位元)
-   插件版本 [例如: 1.0.0]
v2.8.5

**Comment by OpportunityLiu** [comment]
是个白色的图标。。
估计大家都上里站吧。。。
