### ISSUE TITLE
iOS脚本safari内 界面UI和ehunter冲突

### ISSUE THREAD

**Issue by MiyouQ** [EhTagTranslation/EhSyringe#858]
**描述问题**

注射器右下角的图标和ehunter右下的全屏按钮重叠
导致ehunter没法点全屏

**环境**
-   硬件: [iPadmini5]
-   系统: [iOS15]
-   浏览器 [safari]
-   插件版本 [2.8.5]

**Comment by OpportunityLiu** [comment]
按钮应该可以拖动的啊，触屏上没法操作吗

**Comment by MiyouQ** [comment]
> 按钮应该可以拖动的啊，触屏上没法操作吗

对的 触屏上这个针头按钮没法拖动

**Comment by OpportunityLiu** [comment]
Fixed in v2.8.6
