### ISSUE TITLE
修改翻译 Never

### ISSUE THREAD

**Issue by oliver-zhq** [EhTagTranslation/EhSyringe#923]
![image](https://user-images.githubusercontent.com/65083224/176447886-eda18ca7-5412-4879-963c-2eddc157677e.png)
**相关页面**
https://e-hentai.org/g/*
**原文**
Never
**翻译**
从不 --> 从未

**Comment by xioxin** [comment]
这两个翻译冲突了。
虽然写在两个文件中，但是作用在同一个页面。
只能保留其中一个，或者使用一个更通用的词来表达。

**Comment by oliver-zhq** [comment]
> 这两个翻译冲突了。 虽然写在两个文件中，但是作用在同一个页面。 只能保留其中一个，或者使用一个更通用的词来表达。

截图的部分译作 `从未` 更合适，但是另一处译作 `从不` 更合适。

**Comment by OpportunityLiu** [comment]
暂时无解
