### ISSUE TITLE
求教如何使用

### ISSUE THREAD

**Issue by littleshowff** [EhTagTranslation/EhSyringe#949]
作为新人，我看见**安装**里面要安装火狐或是用户脚本，表示不懂，想问手机的E站APP怎么来实现翻译，我下载了这里面几个文件，但没用，应该是我方式不对。

**Comment by xioxin** [comment]
这个是E站网页版的插件，如果第三方的客户端使用了我们的数据实现了标签翻译，在客户端的设置中应该可以找到相关设置。不需要额外安装。
你可以看看你用的APP在不在这个列表里：
https://github.com/EhTagTranslation/Database#%E4%BD%BF%E7%94%A8%E7%BF%BB%E8%AF%91

**Comment by littleshowff** [comment]
谢谢大佬
