### ISSUE TITLE
Submit New Expunge Petition 翻译

### ISSUE THREAD

**Issue by o-liverkk** [EhTagTranslation/EhSyringe#992]
**相关页面**
`https://e-hentai.org/g/2309642/b8326773f8/?act=expunge`
**原文**
` Content has been defaced by adding content-obstructing scanmarks, censorship or advertisements beyond what is present in the original artist release, or has been intentionally degraded to the point where legibility is an issue.`
**翻译**
`画廊内容被污损，添加了与内容无关的扫描水印、审查或广告，超出了原作者发布的内容或被故意降低画质，以至于影响了易读性。`

-----
PS: 这个删除理由需要POWER > 20才能看到

**Comment by xioxin** [comment]
看来我错过了，现在已经没有这个提示了。我会留意的这个提示的，如果遇到的话再加上去。

**Comment by o-liverkk** [comment]
> 当时可能因为该功能还在测试中，所以只出现了一段时间就消失了。[9月12号E-H官方论坛的更新说明](https://forums.e-hentai.org/index.php?showtopic=244935&hl=Added+separate+report+types)中表示，有新的报告类型增加了。现在我这里是可以看到这个提示的。

![image](https://user-images.githubusercontent.com/65083224/190863438-ba563f49-36a9-4465-bc63-199e56d05592.png)
我指的应该不是9-12的更新。[污损](https://forums.e-hentai.org/index.php?showtopic=257275)这个删除原因是今年4月添加的。

**Comment by xioxin** [comment]
如果方便的话查看源代码，将需要翻译的内容相关html（要包括父级标签）发出来。也可以发整页的html。
因为ehs是通过精准匹配，多一个少一个空格都可能导致无法匹配，所以我需要原始的html确保匹配正确。

**Comment by o-liverkk** [comment]
> 如果方便的话查看源代码，将需要翻译的内容相关html（要包括父级标签）发出来。也可以发整页的html。 因为ehs是通过精准匹配，多一个少一个空格都可能导致无法匹配，所以我需要原始的html确保匹配正确。

https://github.com/o-liverkk/public/raw/main/Submit%20New%20Expunge%20Petition
